RobertHeijnSynthesisAlessandroM/WebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainLayer;
using DataAccessLayer;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public List<Advertisement> Advertisements { get; private set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            AdvertisementsManager adsManager = new AdvertisementsManager(new AdvertisementRepository());
            this.Advertisements = adsManager.GetActiveAdvertisements();
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/access_denied.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class access_deniedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/exception_error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class exception_errorModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/login.cshtml.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Reflection.PortableExecutable;
using System.Security.Claims;
using DataAccessLayer;
using DomainLayer;
using WebApp.Pages.Helpers;
using System.Text.Json;

namespace WebApp.Pages
{
    public class loginModel : PageModel
    {
        [BindProperty]
        public Models.Credentials Credentials { get; set; }

        public void OnGet()
        {
            if (Request.Cookies.ContainsKey("RememberMeCookieName"))
            {
                this.Credentials = new Models.Credentials();
                this.Credentials.Username = Request.Cookies["RememberMeCookieName"];
                this.Credentials.RememberMe = true;
            }
        }

        public IActionResult OnPost()
        {
            UserManager userManager = new UserManager(new UserRepository());
            
            if (ModelState.IsValid)
            {
                try
                {
                    int userId = userManager.GetUserId(Credentials.Username, Credentials.Password);

                    // Employees cannot login on the Customer view.
                    if (userManager.GetUser(userId) is Employee)
                    {
                        return RedirectToPage("exception_error");
                    }

                    if (userId != -1)
                    {
                        List<Claim> claims = new List<Claim>();
                        claims.Add(new Claim("id", userId.ToString()));
                        claims.Add(new Claim(ClaimTypes.Email, Credentials.Username));

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));

                        if (this.Credentials.RememberMe)
                        {
                            CookieOptions cookieOptions = new CookieOptions();
                            cookieOptions.Expires = DateTime.Now.AddDays(1);
                            Response.Cookies.Append("RememberMeCookieName", this.Credentials.Username, cookieOptions);
                        }

                        // Saving a new ShoppingCart to a session
                        SessionHelper.SetObjectInSession(HttpContext.Session, "ShoppingCart", new ShoppingCart(new AdvertisementRepository(), new List<CartItem>()));

                        // Redirecting to index (that will have a different layout now)
                        return new RedirectToPageResult("index");
                    }
                }
                catch (Exception e)
                {
                    throw e;
                    return RedirectToPage("exception_error");
                }
                
            }
            return Page();
        }

    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/logout.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class logoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.SignOutAsync();
            return Redirect("/index");

        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/order_details.cshtml.cs
using DataAccessLayer;
using DomainLayer;
using DomainLayer.Exceptions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class order_detailsModel : PageModel
    {
        public Order Order { get; private set; }
        public string Error { get; private set; }
        public Customer Customer { get; private set; }

        public void OnGet(int? id)
        {
            this.Error = "";

            if (id.HasValue)
            {
                UserManager userManager = new UserManager(new UserRepository());
                OrderManager orderManager = new OrderManager(new OrderRepository());

                try
                {
                    Customer customer = (Customer)userManager.GetUser(Convert.ToInt32(User.FindFirst("id").Value));
                    this.Customer = customer;
                    if (userManager.HasOrder(customer, Convert.ToInt32(id)))
                    {
                        this.Order = orderManager.GetOrder(Convert.ToInt32(id));
                    }
                    else
                    {
                        this.Error = "You are not authorized to view this information!";
                    }
                }
                catch(OrderNotFoundException ex)
                {
                    this.Error = ex.Message;
                }
                catch(Exception)
                {
                    Redirect("exception_error");
                }
            }
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/product_details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainLayer;
using DataAccessLayer;
using WebApp.Pages.Helpers;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using System.Net.Http;

namespace WebApp.Pages
{
    public class product_detailsModel : PageModel
    {
        [BindProperty]
        public Models.CartItem CartItem { get; set; }
        public Product Product { get; set; }
        public void OnGet(int? id)
        {
            if (id.HasValue)
            {
                Stock stock = new Stock(new ProductRepository(), new AdvertisementRepository());
                this.Product = stock.GetProduct(Convert.ToInt32(id));
            }
        }

        public IActionResult OnPost(int? id)
        {
            if (ModelState.IsValid)
            {
                // Retrieving the ShoppingCart from Session
                ShoppingCart shoppingCart = SessionHelper.GetCustomObjectFromSession<ShoppingCart>(HttpContext.Session, "ShoppingCart");
                shoppingCart.UseRepository(new AdvertisementRepository());

                // Retrieving the Product that has to be added to the cart
                Stock stock = new Stock(new ProductRepository(), new AdvertisementRepository());
                this.Product = stock.GetProduct(Convert.ToInt32(id));

                // Adding the product and quantity to the shopping cart
                shoppingCart.Add(this.Product, CartItem.Quantity);

                // Storing ShoppingCart to the session again
                SessionHelper.SetObjectInSession(HttpContext.Session, "ShoppingCart", shoppingCart);
                return new RedirectToPageResult("/shopping_cart");
            }
            return Page();
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/products.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainLayer;
using DataAccessLayer;

namespace WebApp.Pages
{
    public class productsModel : PageModel
    {
        public List<Product> Products { get; set; }
        public void OnGet()
        {
            Stock stock = new Stock(new ProductRepository(), new AdvertisementRepository());
            this.Products = stock.GetProducts();
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/profile.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class profileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/registration.cshtml.cs
using DomainLayer;
using DataAccessLayer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApp.Pages
{
    public class registrationModel : PageModel
    {
        [BindProperty]
        public Models.Customer Customer { get; set; }
        public IActionResult OnGet()
        {
            // If user is logged in, he cannot access registration page!

            if(User.Identity.IsAuthenticated)
            {
                return RedirectToPage("index");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                // Hashing the Password
                string hashed = PasswordHandler.HashPassword(Customer.Password);

                // Adding the User
                UserManager userManager = new UserManager(new UserRepository());
                userManager.Add(new Customer(Customer.Email, hashed, Customer.Name, Customer.Surname, Customer.Birthdate, new Address(Customer.Street, Customer.HouseNumber, Customer.City, Customer.PostalCode, Customer.Country), Customer.Phone));

                // Redirecting to Login
                return new RedirectToPageResult("/login");
            }
            return Page();
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/shopping_cart.cshtml.cs
using DataAccessLayer;
using DomainLayer;
using DomainLayer.Enums;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text.Json;
using WebApp.Pages.Helpers;

namespace WebApp.Pages
{
    [Authorize]
    public class shopping_cartModel : PageModel
    {
        [BindProperty]
        public Models.Payment Payment { get; set; }

        public ShoppingCart ShoppingCart { get; private set; }
        public double Total { get; private set; }

        public void OnGet()
        {
            // Retrieving the ShoppingCart from Session
            this.ShoppingCart = SessionHelper.GetCustomObjectFromSession<ShoppingCart>(HttpContext.Session, "ShoppingCart");
            this.ShoppingCart.UseRepository(new AdvertisementRepository());

            // Retrieving the BonusCard of the logged in User
            UserManager userManager = new UserManager(new UserRepository());
            this.Total = this.ShoppingCart.GetTotal(((Customer)userManager.GetUser(Convert.ToInt32(User.FindFirst("id").Value))).BonusCard);
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                // Retrieving the ShoppingCart from the session
                this.ShoppingCart = SessionHelper.GetCustomObjectFromSession<ShoppingCart>(HttpContext.Session, "ShoppingCart");
                this.ShoppingCart.UseRepository(new AdvertisementRepository());

                // Retrieving the customer that confirmed the order & Adding the order
                UserManager userManager = new UserManager(new UserRepository());
                OrderManager orderManager = new OrderManager(new OrderRepository());
                PaymentMethod paymentMethod = (PaymentMethod)Enum.Parse(typeof(PaymentMethod), this.Payment.Method);
                
                try
                {
                    Customer customer = (Customer)userManager.GetUser(Convert.ToInt32(User.FindFirst("id").Value));
                    orderManager.AddOrder(new Order(this.ShoppingCart, paymentMethod, customer));
                }
                catch (Exception e)
                {
                    string error = e.Message;
                    return RedirectToPage("exception_error");
                }

                // Emptying the ShoppingCart in the session
                this.ShoppingCart = new ShoppingCart(new AdvertisementRepository());
                SessionHelper.SetObjectInSession(HttpContext.Session, "ShoppingCart", new ShoppingCart(new AdvertisementRepository(), new List<CartItem>()));
            }
            return Page();
        }

        public IActionResult OnPostRemove(int? id)
        {
            if (id.HasValue)
            {
                // Retrieving the ShoppingCart from the session
                ShoppingCart shoppingCart = SessionHelper.GetCustomObjectFromSession<ShoppingCart>(HttpContext.Session, "ShoppingCart");
                shoppingCart.UseRepository(new AdvertisementRepository());

                // Removing the CartItem from the Cart
                shoppingCart.Remove(Convert.ToInt32(id));

                // Re-Saving the ShoppingCart in the session
                SessionHelper.SetObjectInSession(HttpContext.Session, "ShoppingCart", shoppingCart);
            }
            return RedirectToPage("/shopping_cart");
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/view_orders.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using DomainLayer;
using DataAccessLayer;
using DomainLayer.Exceptions;
using Microsoft.AspNetCore.Authorization;

namespace WebApp.Pages
{
    [Authorize]
    public class view_ordersModel : PageModel
    {
        public List<Order> Orders { get; set; }
        public IActionResult OnGet()
        {
            UserManager userManager = new UserManager(new UserRepository());
            try
            {
                if (userManager.GetUser(Convert.ToInt32(User.FindFirst("id").Value)) is Customer)
                {
                    this.Orders = ((Customer)userManager.GetUser(Convert.ToInt32(User.FindFirst("id").Value))).Orders;
                }
            }
            catch (InvalidIdException e)
            {
                return RedirectToPage("/exception_error");
            }
            return Page();
        }
    }
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/Index.cshtml
@page
@using DomainLayer.Advertisements;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<h1>Welcome to RobertHeijn Shopping Website</h1>
<h3>View Active Discounts</h3>

<ul>
    @foreach(DomainLayer.Advertisement a in Model.Advertisements)
    {
        // ToDo: Could just save enum DiscountType in Advertisement to avoid checking everytime! 
        // ToDo: Could add ToString method in advertisement interface and just call that when i have to display info.
        if (a is AD_TwoForOne)
        {
            <li>
                Discount for: <a href="/product_details?id=@a.Product.Id">@a.Product.Name</a> - Ends: @a.EndDate. : Two For One
            </li>
        }
        else if (a is AD_SecondHalfPrice)
        {
            <li>
                Discount for: <a href="/product_details?id=@a.Product.Id">@a.Product.Name</a> - Ends: @a.EndDate. : Second Half Price
            </li>
        }
        else if (a is AD_TwoForPrice)
        {
            <li>
                Discount for: <a href="/product_details?id=@a.Product.Id">@a.Product.Name</a> - Ends: @a.EndDate. : Two For @(((AD_TwoForPrice)a).Price) €
            </li>
        }
        else if (a is AD_PriceForWeight)
        {
            <li>
                Discount for: <a href="/product_details?id=@a.Product.Id">@a.Product.Name</a> - Ends: @a.EndDate. : @(((AD_PriceForWeight)a).Price) € For @(((AD_PriceForWeight)a).Weight)
            </li>
        }
    }
</ul>
<!--ToDo: implement list for advertisement of discounts-->

<h3>What are you waiting for? Start Shopping!</h3>
<h4>head over to <a asp-area="" asp-page="/products">Products page</a>!</h4>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/access_denied.cshtml
@page
@model WebApp.Pages.access_deniedModel
@{
}

<h1>Access Denied!</h1>
<h3>You're not permitted to access this page.</h3>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/exception_error.cshtml
@page
@model WebApp.Pages.exception_errorModel
@{
}

<h3>Internal Error!</h3>
<div>Consider trying again or contacting the system administrator!</div>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/login.cshtml
@page
@model WebApp.Pages.loginModel
@{
        ViewData["Title"] = "Login";
}

<div id="logform">
    <div id="login-form">
        <div class="title">Login <a href="/index">RobertHeijn</a></div>
        <div class="subtitle">Nice to see you again.</div>

        <form method="post">

            <div class="input-container ic1">
                <span asp-validation-for="Credentials.Username"></span>
                <input asp-for="Credentials.Username" placeholder="Email" id="email" class="input">
                <div class="cut cut-short"></div>
            </div>

            <div class="input-container ic2">
                <span asp-validation-for="Credentials.Password"></span>
                <input asp-for="Credentials.Password" id="password" class="input" placeholder="Password">
            </div>

            <div class="input-container" id="login-remember-me">
                <input asp-for="Credentials.RememberMe">
                <label asp-for="Credentials.RememberMe">Remember Me</label>
            </div>

            <button type="text" class="submit" id="login-form-submit">Login</button>

            <div class="subtitle2">Don't have an account? <a href="registration">Sign up!</a></div>

        </form>

    </div>
</div>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/logout.cshtml
@page
@model WebApp.Pages.logoutModel
@{
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/order_details.cshtml
@page
@using DomainLayer;
@model WebApp.Pages.order_detailsModel
@{
}

<h3>Order Number: @Model.Order.Id</h3>

<div>Ordered: @Model.Order.OrderDate</div>
<div>Delivery Date: @Model.Order.DeliveryDate</div>
<div>Delivery Address: @Model.Customer.Address.ToString()</div>
<div>Status: @Model.Order.OrderStatus</div>
<div>Payed with: @Model.Order.PaymentMethod</div>

<div><b>Ordered Products</b></div>
<ul>
    @foreach(OrderItem o in Model.Order.OrderItems)
    {
        if (o.Discount != 0)
        {
            <li>
                @o.Quantity X @o.Product.Name: @o.GetTotal() € [Saved @o.Discount €]
            </li>
        }
        else 
        {
            <li>
                @o.Quantity X @o.Product.Name: @o.GetTotal() €
            </li>
        }
    }
</ul>

<div><b>Order Total: @Model.Order.GetTotal() €</b></div>


@if (Model.Error != "")
{
    <div class="error">Error: @Model.Error</div>
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/product_details.cshtml
@page
@model WebApp.Pages.product_detailsModel
@{
    ViewData["Title"] = $"{Model.Product.Name}";
}

<h2>@Model.Product.Name</h2>

<div>Category: @Model.Product.Category</div>
<div>Sub-Category: @Model.Product.SubCategory</div>
@if (@Model.Product.Unit != DomainLayer.Enums.Unit.NO_UNIT)
{
    <div>Unit: @Model.Product.Unit</div>
}
<div>Price: @Model.Product.Price€</div>

<form method="post">
    <label asp-for="CartItem.Quantity">Select Amount</label>
    <input asp-for="CartItem.Quantity" type="number" value="1"></input>
    <br />
    <button type="submit" asp-route="@Model.Product.Id">Add to Cart</button>
</form>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/products.cshtml
@page
@model WebApp.Pages.productsModel
@{
    ViewData["Title"] = "Products Catalogue";
}

<ul>
    @foreach (DomainLayer.Product p in Model.Products)
    {
        <li>
            <a href="/product_details?id=@p.Id">@p.Name</a> - @p.Price €
        </li>
    }
</ul>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/profile.cshtml
@page
@model WebApp.Pages.profileModel
@{
    ViewData["Title"] = "Profile";
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/registration.cshtml
@page
@model WebApp.Pages.registrationModel
@{
    ViewData["Title"] = "Sign Up";
}

<section class="form">

    <form method="post">

        <div class="title" style="color:  rgb(18, 188, 132);">Sign Up</div>
        <h4>Your first step towards online shopping!</h4>

        <div class="input-container">
            <span asp-validation-for="Customer.Email" class="field-validation-error"></span>
            <input asp-for="Customer.Email" class="input" placeholder="Email" size="30" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Password" class="field-validation-error"></span>
            <input asp-for="Customer.Password" class="input" size="30" type="password" placeholder="Password" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Name" class="field-validation-error"></span>
            <input asp-for="Customer.Name" class="input" size="30" placeholder="Name" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Surname" class="field-validation-error"></span>
            <input asp-for="Customer.Surname" class="input" size="30" placeholder="Surname" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Birthdate" class="field-validation-error"></span>
            <input asp-for="Customer.Birthdate" class="input" size="30" type="date" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Street" class="field-validation-error"></span>
            <input asp-for="Customer.Street" class="input" size="30" placeholder="Street" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.HouseNumber" class="field-validation-error"></span>
            <input asp-for="Customer.HouseNumber" class="input" size="30" placeholder="House Number" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.City" class="field-validation-error"></span>
            <input asp-for="Customer.City" class="input" size="30" placeholder="City" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.PostalCode" class="field-validation-error"></span>
            <input asp-for="Customer.PostalCode" class="input" size="30" placeholder="PostalCode" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Country" class="field-validation-error"></span>
            <input asp-for="Customer.Country" class="input" size="30" placeholder="Country" required>
        </div>

        <br>

        <div class="input-container">
            <span asp-validation-for="Customer.Phone" class="field-validation-error"></span>
            <input asp-for="Customer.Phone" class="input" size="30" placeholder="Phone" required>
        </div>

        <br><br>

        <button type="submit" class="submit" id="form-submit">submit</button>

    </form>
</section>

RobertHeijnSynthesisAlessandroM/WebApp/Pages/shopping_cart.cshtml
@page
@model WebApp.Pages.shopping_cartModel
@{
    ViewData["Title"] = "Shopping Cart";
}

<h1>Shopping Cart</h1>

<form asp-page-handler="remove" method="post">
    <ul>
    @foreach (DomainLayer.CartItem c in Model.ShoppingCart.Products)
    {
        if (@c.GetDiscount() > 0)
        {
            <li>
                @c.Product.Name - Quantity: @c.Quantity - @c.GetTotal()€ (Saving @c.GetDiscount()€) [<button type="submit" name="id" value="@c.Id">Remove</button>]
            </li>
        }
        else
        {
            <li>
                    @c.Product.Name - Quantity: @c.Quantity - @c.GetTotal()€ [<button type="submit" name="id" value="@c.Id">Remove</button>]
            </li>
        }
        
    }
</ul>
</form>


<div><b>Cart Total: @Model.Total €</b></div>

<form method="post">
    <span asp-validation-for="Payment.Method"></span>
    <select asp-for="Payment.Method">
        <option value="CREDIT_CARD">Credit Card</option>
        <option value="DEBIT_CARD">Debit Card</option>
        <option value="PAYPAL">PayPal</option>
        <option value="GOOGLE_PAY">Google Pay</option>
        <option value="APPLE_PAY">Apple Pay</option>
    </select>
    <button type="submit">Confirm Order</button>
</form>


@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

RobertHeijnSynthesisAlessandroM/WebApp/Pages/view_orders.cshtml
@page
@model WebApp.Pages.view_ordersModel
@{
}

<h1>Your Orders:</h1>

<ul>
    @foreach (DomainLayer.Order o in Model.Orders)
    {
        <li>
            <a href="/order_details?id=@o.Id">Nr. @o.Id</a> - Ordered @o.OrderDate [@o.GetTotal() €] : @o.OrderStatus
        </li>
    }
</ul>